USE ROLE ACCOUNTADMIN;
USE WAREHOUSE CANCER_ANALYTICS_WH;
USE DATABASE CANCER_ANALYTICS_DB;

CREATE OR REPLACE TEMP TABLE STG_PATIENTS AS
SELECT
    PATIENT_ID,
    NAME AS PATIENT_NAME,
    DOB,
    GENDER,
    STAGE,
    BMI,
    SMOKING_STATUS,
    FAMILY_HISTORY_CANCER,
    RADIATION_EXPOSURE,
    PREVIOUS_CANCERS,
    AGE,
    SHA2(CONCAT_WS('||',
        COALESCE(NAME, ''),
        COALESCE(TO_VARCHAR(DOB), ''),
        COALESCE(GENDER, ''),
        COALESCE(STAGE, ''),
        COALESCE(TO_VARCHAR(BMI), ''),
        COALESCE(SMOKING_STATUS, ''),
        COALESCE(FAMILY_HISTORY_CANCER, ''),
        COALESCE(RADIATION_EXPOSURE, ''),
        COALESCE(PREVIOUS_CANCERS, ''),
        COALESCE(TO_VARCHAR(AGE), '')
    ), 256) AS RECORD_HASH
FROM RAW.PATIENTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY INGESTED_AT DESC NULLS LAST) = 1;

UPDATE DW.DIM_PATIENTS TARGET
SET VALID_TO = CURRENT_TIMESTAMP(),
    IS_CURRENT = FALSE
FROM STG_PATIENTS SRC
WHERE TARGET.PATIENT_ID = SRC.PATIENT_ID
  AND TARGET.IS_CURRENT = TRUE
  AND TARGET.RECORD_HASH <> SRC.RECORD_HASH;

INSERT INTO DW.DIM_PATIENTS (
    PATIENT_ID,
    PATIENT_NAME,
    DOB,
    GENDER,
    STAGE,
    BMI,
    SMOKING_STATUS,
    FAMILY_HISTORY_CANCER,
    RADIATION_EXPOSURE,
    PREVIOUS_CANCERS,
    AGE,
    RECORD_HASH,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT
)
SELECT
    SRC.PATIENT_ID,
    SRC.PATIENT_NAME,
    SRC.DOB,
    SRC.GENDER,
    SRC.STAGE,
    SRC.BMI,
    SRC.SMOKING_STATUS,
    SRC.FAMILY_HISTORY_CANCER,
    SRC.RADIATION_EXPOSURE,
    SRC.PREVIOUS_CANCERS,
    SRC.AGE,
    SRC.RECORD_HASH,
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
FROM STG_PATIENTS SRC
LEFT JOIN DW.DIM_PATIENTS CURR
    ON CURR.PATIENT_ID = SRC.PATIENT_ID
   AND CURR.IS_CURRENT = TRUE
WHERE CURR.PATIENT_ID IS NULL
   OR CURR.RECORD_HASH <> SRC.RECORD_HASH;

CREATE OR REPLACE TEMP TABLE STG_CANCER AS
SELECT
    PATIENT_ID,
    PATIENT_NAME,
    CANCER_TYPE,
    ICD_CODE,
    STAGE,
    DESCRIPTION,
    TUMOR_MARKERS,
    SHA2(CONCAT_WS('||',
        COALESCE(PATIENT_NAME, ''),
        COALESCE(CANCER_TYPE, ''),
        COALESCE(ICD_CODE, ''),
        COALESCE(STAGE, ''),
        COALESCE(DESCRIPTION, ''),
        COALESCE(TUMOR_MARKERS, '')
    ), 256) AS RECORD_HASH
FROM RAW.CANCER_CATALOG
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PATIENT_ID, CANCER_TYPE
    ORDER BY INGESTED_AT DESC NULLS LAST
) = 1;

UPDATE DW.DIM_CANCER_CATALOG TARGET
SET VALID_TO = CURRENT_TIMESTAMP(),
    IS_CURRENT = FALSE
FROM STG_CANCER SRC
WHERE TARGET.PATIENT_ID = SRC.PATIENT_ID
  AND TARGET.CANCER_TYPE = SRC.CANCER_TYPE
  AND TARGET.IS_CURRENT = TRUE
  AND TARGET.RECORD_HASH <> SRC.RECORD_HASH;

INSERT INTO DW.DIM_CANCER_CATALOG (
    PATIENT_ID,
    PATIENT_NAME,
    CANCER_TYPE,
    ICD_CODE,
    STAGE,
    DESCRIPTION,
    TUMOR_MARKERS,
    RECORD_HASH,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT
)
SELECT
    SRC.PATIENT_ID,
    SRC.PATIENT_NAME,
    SRC.CANCER_TYPE,
    SRC.ICD_CODE,
    SRC.STAGE,
    SRC.DESCRIPTION,
    SRC.TUMOR_MARKERS,
    SRC.RECORD_HASH,
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
FROM STG_CANCER SRC
LEFT JOIN DW.DIM_CANCER_CATALOG CURR
    ON CURR.PATIENT_ID = SRC.PATIENT_ID
   AND CURR.CANCER_TYPE = SRC.CANCER_TYPE
   AND CURR.IS_CURRENT = TRUE
WHERE CURR.PATIENT_ID IS NULL
   OR CURR.RECORD_HASH <> SRC.RECORD_HASH;

CREATE OR REPLACE TEMP TABLE STG_PROVIDERS AS
SELECT
    PROVIDER_ID,
    NAME AS PROVIDER_NAME,
    SPECIALTY,
    LOCATION,
    YEARS_OF_EXPERIENCE AS EXPERIENCE_YEARS
FROM RAW.PROVIDERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY PROVIDER_ID ORDER BY INGESTED_AT DESC NULLS LAST) = 1;

TRUNCATE TABLE DW.DIM_PROVIDERS;

INSERT INTO DW.DIM_PROVIDERS (
    PROVIDER_ID,
    PROVIDER_NAME,
    SPECIALTY,
    LOCATION,
    EXPERIENCE_YEARS,
    LOADED_AT
)
SELECT
    PROVIDER_ID,
    PROVIDER_NAME,
    SPECIALTY,
    LOCATION,
    EXPERIENCE_YEARS,
    CURRENT_TIMESTAMP()
FROM STG_PROVIDERS;

TRUNCATE TABLE DW.DIM_DATE;

INSERT INTO DW.DIM_DATE (
    DATE_SK,
    ENCOUNTER_DATE,
    YEAR,
    MONTH,
    DAY,
    QUARTER,
    LOADED_AT
)
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(DATE, 'YYYYMMDD')) AS DATE_SK,
    DATE AS ENCOUNTER_DATE,
    YEAR(DATE) AS YEAR,
    MONTH(DATE) AS MONTH,
    DAY(DATE) AS DAY,
    QUARTER(DATE) AS QUARTER,
    CURRENT_TIMESTAMP()
FROM RAW.ENCOUNTERS
WHERE DATE IS NOT NULL;

TRUNCATE TABLE DW.FACT_ENCOUNTERS;

INSERT INTO DW.FACT_ENCOUNTERS (
    ENCOUNTER_ID,
    PATIENT_SK,
    CANCER_SK,
    PROVIDER_SK,
    PROVIDER_ID,
    DATE_SK,
    PATIENT_ID,
    ENCOUNTER_DATE,
    TREATMENT,
    DRUG_REGIMEN,
    NUMBER_OF_CYCLES,
    TREATMENT_RESPONSE_SCORE,
    OUTCOME,
    BILLING_ID,
    BILLING_AMOUNT,
    INSURANCE,
    PAYMENT_STATUS,
    PIPELINE_RUN_ID,
    LOADED_AT
)
SELECT
    E.ENCOUNTER_ID,
    P.PATIENT_SK,
    C.CANCER_SK,
    PR.PROVIDER_SK,
    PR.PROVIDER_ID,
    D.DATE_SK,
    E.PATIENT_ID,
    E.DATE AS ENCOUNTER_DATE,
    E.TREATMENT,
    E.DRUG_REGIMEN,
    E.NUMBER_OF_CYCLES,
    E.TREATMENT_RESPONSE_SCORE,
    E.OUTCOME,
    B.BILLING_ID,
    B.AMOUNT AS BILLING_AMOUNT,
    B.INSURANCE,
    B.PAYMENT_STATUS,
    E.PIPELINE_RUN_ID,
    CURRENT_TIMESTAMP()
FROM RAW.ENCOUNTERS E
LEFT JOIN DW.DIM_PATIENTS P
    ON E.PATIENT_ID = P.PATIENT_ID
   AND P.IS_CURRENT = TRUE
LEFT JOIN DW.DIM_CANCER_CATALOG C
    ON E.PATIENT_ID = C.PATIENT_ID
   AND C.IS_CURRENT = TRUE
LEFT JOIN (
    SELECT
        PROVIDER_SK,
        PROVIDER_ID,
        ROW_NUMBER() OVER (ORDER BY PROVIDER_ID) - 1 AS PROVIDER_INDEX
    FROM DW.DIM_PROVIDERS
) PR
    ON MOD(ABS(HASH(E.ENCOUNTER_ID)), (SELECT COUNT(*) FROM DW.DIM_PROVIDERS)) = PR.PROVIDER_INDEX
LEFT JOIN DW.DIM_DATE D
    ON E.DATE = D.ENCOUNTER_DATE
LEFT JOIN RAW.BILLING B
    ON E.ENCOUNTER_ID = B.ENCOUNTER_ID;

TRUNCATE TABLE DW.BRIDGE_ENCOUNTER_PROVIDER;

INSERT INTO DW.BRIDGE_ENCOUNTER_PROVIDER (
    ENCOUNTER_ID,
    PROVIDER_SK,
    PROVIDER_ID,
    ASSIGNMENT_METHOD,
    LOADED_AT
)
SELECT
    ENCOUNTER_ID,
    PROVIDER_SK,
    PROVIDER_ID,
    'HASH_ENCOUNTER_PROVIDER_ASSIGNMENT',
    CURRENT_TIMESTAMP()
FROM DW.FACT_ENCOUNTERS
WHERE PROVIDER_SK IS NOT NULL;

INSERT INTO OPS.PIPELINE_AUDIT (
    PIPELINE_RUN_ID,
    PIPELINE_STEP,
    TABLE_NAME,
    SOURCE_COUNT,
    VALID_COUNT,
    REJECT_COUNT,
    ROW_COUNT,
    STATUS,
    RECORDED_AT
)
SELECT
    MAX(E.PIPELINE_RUN_ID),
    'raw_to_dw',
    'fact_encounters',
    COUNT(*),
    COUNT(*),
    0,
    COUNT(*),
    'SUCCESS',
    CURRENT_TIMESTAMP()
FROM RAW.ENCOUNTERS E;

CREATE OR REPLACE VIEW SEMANTIC.V_PROVIDER_PERFORMANCE AS
SELECT
    F.PROVIDER_ID,
    PR.PROVIDER_NAME,
    PR.SPECIALTY,
    PR.LOCATION,
    COUNT(DISTINCT F.ENCOUNTER_ID) AS ENCOUNTER_COUNT,
    COUNT(DISTINCT F.PATIENT_ID) AS PATIENT_COUNT,
    AVG(F.TREATMENT_RESPONSE_SCORE) AS AVG_TREATMENT_RESPONSE_SCORE,
    SUM(F.BILLING_AMOUNT) AS TOTAL_BILLING_AMOUNT,
    AVG(F.BILLING_AMOUNT) AS AVG_BILLING_AMOUNT
FROM DW.FACT_ENCOUNTERS F
LEFT JOIN DW.DIM_PROVIDERS PR
    ON F.PROVIDER_SK = PR.PROVIDER_SK
GROUP BY 1,2,3,4;
