USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE CANCER_ANALYTICS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE CANCER_ANALYTICS_DB;
USE DATABASE CANCER_ANALYTICS_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA DW;
CREATE OR REPLACE SCHEMA SEMANTIC;
CREATE OR REPLACE SCHEMA OPS;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FILE_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE RAW.RAW_CSV_STAGE
    FILE_FORMAT = RAW.CSV_FILE_FORMAT;

CREATE OR REPLACE ROLE CANCER_ANALYTICS_ADMIN;
CREATE OR REPLACE ROLE CANCER_ANALYTICS_ANALYST;
CREATE OR REPLACE ROLE CANCER_ANALYTICS_RESTRICTED;

GRANT USAGE ON WAREHOUSE CANCER_ANALYTICS_WH TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT USAGE ON WAREHOUSE CANCER_ANALYTICS_WH TO ROLE CANCER_ANALYTICS_ANALYST;
GRANT USAGE ON WAREHOUSE CANCER_ANALYTICS_WH TO ROLE CANCER_ANALYTICS_RESTRICTED;

GRANT USAGE ON DATABASE CANCER_ANALYTICS_DB TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT USAGE ON DATABASE CANCER_ANALYTICS_DB TO ROLE CANCER_ANALYTICS_ANALYST;
GRANT USAGE ON DATABASE CANCER_ANALYTICS_DB TO ROLE CANCER_ANALYTICS_RESTRICTED;

GRANT USAGE ON SCHEMA CANCER_ANALYTICS_DB.RAW TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT USAGE ON SCHEMA CANCER_ANALYTICS_DB.DW TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT USAGE ON SCHEMA CANCER_ANALYTICS_DB.SEMANTIC TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT USAGE ON SCHEMA CANCER_ANALYTICS_DB.OPS TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT USAGE ON SCHEMA CANCER_ANALYTICS_DB.SEMANTIC TO ROLE CANCER_ANALYTICS_ANALYST;
GRANT USAGE ON SCHEMA CANCER_ANALYTICS_DB.DW TO ROLE CANCER_ANALYTICS_RESTRICTED;
GRANT READ, WRITE ON STAGE CANCER_ANALYTICS_DB.RAW.RAW_CSV_STAGE TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT USAGE ON FILE FORMAT CANCER_ANALYTICS_DB.RAW.CSV_FILE_FORMAT TO ROLE CANCER_ANALYTICS_ADMIN;

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE CANCER_ANALYTICS_WH;
USE DATABASE CANCER_ANALYTICS_DB;

CREATE OR REPLACE TABLE RAW.PATIENTS (
    PATIENT_ID STRING,
    NAME STRING,
    DOB DATE,
    GENDER STRING,
    STAGE STRING,
    BMI NUMBER(10,2),
    SMOKING_STATUS STRING,
    FAMILY_HISTORY_CANCER STRING,
    RADIATION_EXPOSURE STRING,
    PREVIOUS_CANCERS STRING,
    AGE NUMBER(10,0),
    PIPELINE_RUN_ID STRING,
    INGESTED_AT TIMESTAMP_NTZ,
    SOURCE_FILE_NAME STRING
);

CREATE OR REPLACE TABLE RAW.PROVIDERS (
    PROVIDER_ID STRING,
    NAME STRING,
    SPECIALTY STRING,
    LOCATION STRING,
    YEARS_OF_EXPERIENCE NUMBER(10,0),
    PIPELINE_RUN_ID STRING,
    INGESTED_AT TIMESTAMP_NTZ,
    SOURCE_FILE_NAME STRING
);

CREATE OR REPLACE TABLE RAW.ENCOUNTERS (
    ENCOUNTER_ID STRING,
    PATIENT_ID STRING,
    DATE DATE,
    TREATMENT STRING,
    DRUG_REGIMEN STRING,
    NUMBER_OF_CYCLES NUMBER(10,0),
    TREATMENT_RESPONSE_SCORE NUMBER(10,2),
    OUTCOME STRING,
    PIPELINE_RUN_ID STRING,
    INGESTED_AT TIMESTAMP_NTZ,
    SOURCE_FILE_NAME STRING
);

CREATE OR REPLACE TABLE RAW.CANCER_CATALOG (
    PATIENT_ID STRING,
    PATIENT_NAME STRING,
    CANCER_TYPE STRING,
    ICD_CODE STRING,
    STAGE STRING,
    DESCRIPTION STRING,
    TUMOR_MARKERS STRING,
    PIPELINE_RUN_ID STRING,
    INGESTED_AT TIMESTAMP_NTZ,
    SOURCE_FILE_NAME STRING
);

CREATE OR REPLACE TABLE RAW.BILLING (
    BILLING_ID STRING,
    ENCOUNTER_ID STRING,
    PATIENT_ID STRING,
    PATIENT_NAME STRING,
    AMOUNT NUMBER(18,2),
    INSURANCE STRING,
    PAYMENT_STATUS STRING,
    PIPELINE_RUN_ID STRING,
    INGESTED_AT TIMESTAMP_NTZ,
    SOURCE_FILE_NAME STRING
);

CREATE OR REPLACE TABLE OPS.PIPELINE_AUDIT (
    PIPELINE_RUN_ID STRING,
    PIPELINE_STEP STRING,
    TABLE_NAME STRING,
    SOURCE_COUNT NUMBER,
    VALID_COUNT NUMBER,
    REJECT_COUNT NUMBER,
    ROW_COUNT NUMBER,
    STATUS STRING,
    RECORDED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE OPS.REJECTED_RECORDS (
    PIPELINE_RUN_ID STRING,
    PIPELINE_STEP STRING,
    TABLE_NAME STRING,
    REJECT_REASON STRING,
    REJECTED_AT TIMESTAMP_NTZ,
    RECORD_PAYLOAD VARIANT
);

CREATE OR REPLACE TABLE DW.DIM_PATIENTS (
    PATIENT_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PATIENT_ID STRING,
    PATIENT_NAME STRING,
    DOB DATE,
    GENDER STRING,
    STAGE STRING,
    BMI NUMBER(10,2),
    SMOKING_STATUS STRING,
    FAMILY_HISTORY_CANCER STRING,
    RADIATION_EXPOSURE STRING,
    PREVIOUS_CANCERS STRING,
    AGE NUMBER(10,0),
    RECORD_HASH STRING,
    VALID_FROM TIMESTAMP_NTZ,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);

CREATE OR REPLACE TABLE DW.DIM_CANCER_CATALOG (
    CANCER_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PATIENT_ID STRING,
    PATIENT_NAME STRING,
    CANCER_TYPE STRING,
    ICD_CODE STRING,
    STAGE STRING,
    DESCRIPTION STRING,
    TUMOR_MARKERS STRING,
    RECORD_HASH STRING,
    VALID_FROM TIMESTAMP_NTZ,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);

CREATE OR REPLACE TABLE DW.DIM_PROVIDERS (
    PROVIDER_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    PROVIDER_ID STRING,
    PROVIDER_NAME STRING,
    SPECIALTY STRING,
    LOCATION STRING,
    EXPERIENCE_YEARS NUMBER(10,0),
    LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DW.DIM_DATE (
    DATE_SK NUMBER,
    ENCOUNTER_DATE DATE,
    YEAR NUMBER,
    MONTH NUMBER,
    DAY NUMBER,
    QUARTER NUMBER,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DW.FACT_ENCOUNTERS (
    ENCOUNTER_ID STRING,
    PATIENT_SK NUMBER,
    CANCER_SK NUMBER,
    PROVIDER_SK NUMBER,
    PROVIDER_ID STRING,
    DATE_SK NUMBER,
    PATIENT_ID STRING,
    ENCOUNTER_DATE DATE,
    TREATMENT STRING,
    DRUG_REGIMEN STRING,
    NUMBER_OF_CYCLES NUMBER(10,0),
    TREATMENT_RESPONSE_SCORE NUMBER(10,2),
    OUTCOME STRING,
    BILLING_ID STRING,
    BILLING_AMOUNT NUMBER(18,2),
    INSURANCE STRING,
    PAYMENT_STATUS STRING,
    PIPELINE_RUN_ID STRING,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DW.BRIDGE_ENCOUNTER_PROVIDER (
    ENCOUNTER_ID STRING,
    PROVIDER_SK NUMBER,
    PROVIDER_ID STRING,
    ASSIGNMENT_METHOD STRING,
    LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE MASKING POLICY SEMANTIC.PATIENT_ID_MASK AS (VAL STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('CANCER_ANALYTICS_ADMIN', 'ACCOUNTADMIN') THEN VAL
        ELSE REGEXP_REPLACE(VAL, '(^...).*', '\\1****')
    END;

CREATE OR REPLACE MASKING POLICY SEMANTIC.PATIENT_NAME_MASK AS (VAL STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('CANCER_ANALYTICS_ADMIN', 'ACCOUNTADMIN') THEN VAL
        ELSE 'REDACTED'
    END;

ALTER TABLE DW.DIM_PATIENTS MODIFY COLUMN PATIENT_ID SET MASKING POLICY SEMANTIC.PATIENT_ID_MASK;
ALTER TABLE DW.DIM_PATIENTS MODIFY COLUMN PATIENT_NAME SET MASKING POLICY SEMANTIC.PATIENT_NAME_MASK;
ALTER TABLE DW.DIM_CANCER_CATALOG MODIFY COLUMN PATIENT_ID SET MASKING POLICY SEMANTIC.PATIENT_ID_MASK;
ALTER TABLE DW.DIM_CANCER_CATALOG MODIFY COLUMN PATIENT_NAME SET MASKING POLICY SEMANTIC.PATIENT_NAME_MASK;

CREATE OR REPLACE VIEW DW.DIM_PATIENTS_CURRENT AS
SELECT *
FROM DW.DIM_PATIENTS
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW DW.DIM_CANCER_CATALOG_CURRENT AS
SELECT *
FROM DW.DIM_CANCER_CATALOG
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW SEMANTIC.V_ENCOUNTER_OVERVIEW AS
SELECT
    F.ENCOUNTER_ID,
    F.ENCOUNTER_DATE,
    F.TREATMENT,
    F.DRUG_REGIMEN,
    F.NUMBER_OF_CYCLES,
    F.TREATMENT_RESPONSE_SCORE,
    F.OUTCOME,
    F.BILLING_AMOUNT,
    F.INSURANCE,
    F.PAYMENT_STATUS,
    F.PROVIDER_ID,
    PR.PROVIDER_NAME,
    PR.SPECIALTY AS PROVIDER_SPECIALTY,
    PR.LOCATION AS PROVIDER_LOCATION,
    P.PATIENT_ID,
    P.PATIENT_NAME,
    P.GENDER,
    P.AGE,
    P.SMOKING_STATUS,
    C.CANCER_TYPE,
    C.STAGE
FROM DW.FACT_ENCOUNTERS F
LEFT JOIN DW.DIM_PATIENTS_CURRENT P
    ON F.PATIENT_SK = P.PATIENT_SK
LEFT JOIN DW.DIM_CANCER_CATALOG_CURRENT C
    ON F.CANCER_SK = C.CANCER_SK
LEFT JOIN DW.DIM_PROVIDERS PR
    ON F.PROVIDER_SK = PR.PROVIDER_SK;

CREATE OR REPLACE VIEW SEMANTIC.V_FINANCIAL_ANALYTICS AS
SELECT
    ENCOUNTER_DATE,
    TREATMENT,
    INSURANCE,
    PAYMENT_STATUS,
    COUNT(DISTINCT ENCOUNTER_ID) AS ENCOUNTER_COUNT,
    SUM(BILLING_AMOUNT) AS TOTAL_BILLING_AMOUNT,
    AVG(BILLING_AMOUNT) AS AVG_BILLING_AMOUNT
FROM DW.FACT_ENCOUNTERS
GROUP BY 1,2,3,4;

CREATE OR REPLACE VIEW SEMANTIC.V_PROVIDER_PERFORMANCE AS
SELECT
    F.PROVIDER_ID,
    PR.PROVIDER_NAME,
    PR.SPECIALTY,
    PR.LOCATION,
    COUNT(DISTINCT F.ENCOUNTER_ID) AS ENCOUNTER_COUNT,
    COUNT(DISTINCT F.PATIENT_ID) AS PATIENT_COUNT,
    AVG(F.TREATMENT_RESPONSE_SCORE) AS AVG_TREATMENT_RESPONSE_SCORE,
    SUM(F.BILLING_AMOUNT) AS TOTAL_BILLING_AMOUNT,
    AVG(F.BILLING_AMOUNT) AS AVG_BILLING_AMOUNT
FROM DW.FACT_ENCOUNTERS F
LEFT JOIN DW.DIM_PROVIDERS PR
    ON F.PROVIDER_SK = PR.PROVIDER_SK
GROUP BY 1,2,3,4;

GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA DW TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA OPS TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA DW TO ROLE CANCER_ANALYTICS_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA SEMANTIC TO ROLE CANCER_ANALYTICS_ADMIN;

GRANT SELECT ON ALL VIEWS IN SCHEMA SEMANTIC TO ROLE CANCER_ANALYTICS_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA DW TO ROLE CANCER_ANALYTICS_RESTRICTED;

COMMENT ON DATABASE CANCER_ANALYTICS_DB IS
'Cancer analytics warehouse with RAW, DW, SEMANTIC, and OPS schemas for operational and financial oncology reporting.';

-- After running this setup script:
-- 1. Upload source extracts into the Snowflake internal stage with `python utils/load_stage_to_snowflake.py`
-- 2. Run `python snowflake/snowpark_transform.py` or `snowflake/load_dw_from_raw.sql`
-- 3. Export a local gold layer with `python utils/export_gold_from_snowflake.py`
